// @ts-nocheck
/**
 * dice-config-backup-active-key-to-preset-key.ts
 * Feature-Sliced 模块（工厂版，DI 注入依赖）。
 */
import { STORAGE_KEY_ACTION_PRESETS, STORAGE_KEY_ACTIVE_ACTION_PRESET, STORAGE_KEY_ACTIVE_ADVANCED_PRESET, STORAGE_KEY_ACTIVE_ATTR_PRESET, STORAGE_KEY_ACTIVE_DASHBOARD_PRESET, STORAGE_KEY_ACTIVE_PRESET, STORAGE_KEY_ACTIVE_RENDER_PRESET, STORAGE_KEY_ACTIVE_TABLE_TEMPLATE_REQUIREMENT_PRESET, STORAGE_KEY_ADVANCED_PRESETS, STORAGE_KEY_ATTRIBUTE_PRESETS, STORAGE_KEY_DASHBOARD_PRESETS, STORAGE_KEY_LAST_PRESET, STORAGE_KEY_PRESETS, STORAGE_KEY_REGEX_ACTIVE_PRESET, STORAGE_KEY_REGEX_PRESETS, STORAGE_KEY_RENDER_PRESETS, STORAGE_KEY_TABLE_TEMPLATE_REQUIREMENT_PRESETS } from '../../shared/storage-keys';
export function createDiceConfigBackupActiveKeyToPresetKey(deps: any) {
  const DICE_CONFIG_BACKUP_ACTIVE_KEY_TO_PRESET_KEY: Record<string, string> = {
    [STORAGE_KEY_LAST_PRESET]: STORAGE_KEY_ADVANCED_PRESETS,
    [STORAGE_KEY_ACTIVE_ADVANCED_PRESET]: STORAGE_KEY_ADVANCED_PRESETS,
    [STORAGE_KEY_ACTIVE_ATTR_PRESET]: STORAGE_KEY_ATTRIBUTE_PRESETS,
    [STORAGE_KEY_ACTIVE_ACTION_PRESET]: STORAGE_KEY_ACTION_PRESETS,
    [STORAGE_KEY_ACTIVE_DASHBOARD_PRESET]: STORAGE_KEY_DASHBOARD_PRESETS,
    [STORAGE_KEY_ACTIVE_RENDER_PRESET]: STORAGE_KEY_RENDER_PRESETS,
    [STORAGE_KEY_ACTIVE_TABLE_TEMPLATE_REQUIREMENT_PRESET]: STORAGE_KEY_TABLE_TEMPLATE_REQUIREMENT_PRESETS,
    [STORAGE_KEY_ACTIVE_PRESET]: STORAGE_KEY_PRESETS,
    [STORAGE_KEY_REGEX_ACTIVE_PRESET]: STORAGE_KEY_REGEX_PRESETS,
  };
  return DICE_CONFIG_BACKUP_ACTIVE_KEY_TO_PRESET_KEY;
}
