// @ts-nocheck
// 来源：src/features/dice/index.ts 章节 idx=9「ValidationRuleManager - 数据验证规则系统」
// 原行范围：3153-3580（含 banner 3150-3580）；拆分批次 2；外部 closure 依赖：0
  // ========================================
  // ValidationRuleManager - 数据验证规则系统
  // ========================================
  const STORAGE_KEY_VALIDATION_RULES = 'acu_validation_rules_v1';
  const STORAGE_KEY_VALIDATION_ENABLED = 'acu_validation_enabled_v1';
  const STORAGE_KEY_VALIDATION_MODE = 'acu_validation_mode'; // 数据验证模式（只显示验证错误）

  // 规则类型信息（用于 UI 显示和分组）
  const RULE_TYPE_INFO = {
    // 表级规则
    tableReadonly: { name: '表级只读', scope: 'table', icon: 'fa-lock', desc: '禁止修改整个表' },
    rowLimit: { name: '行数限制', scope: 'table', icon: 'fa-arrows-up-down', desc: '限制表的行数范围' },
    sequence: { name: '序列递增', scope: 'table', icon: 'fa-sort-numeric-up', desc: '检查字段值是否严格递增' },
    // 字段级规则
    required: { name: '必填', scope: 'field', icon: 'fa-asterisk', desc: '字段不能为空' },
    format: { name: '格式验证', scope: 'field', icon: 'fa-font', desc: '正则表达式匹配' },
    enum: { name: '枚举验证', scope: 'field', icon: 'fa-list', desc: '值必须在列表中' },
    numeric: { name: '数值范围', scope: 'field', icon: 'fa-hashtag', desc: '数值必须在范围内' },
    relation: { name: '关联验证', scope: 'field', icon: 'fa-link', desc: '引用其他表的值' },
    keyValue: { name: '键值对验证', scope: 'field', icon: 'fa-key', desc: '验证键值对格式和数值范围' },
  };

  // 内置验证规则定义
  const BUILTIN_VALIDATION_RULES = [
    // 总结表编码递增验证
    {
      id: 'summary_code_sequence',
      name: '总结表编码递增',
      description: '编码索引必须从AM0001开始严格递增，不可跳号或重复',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '总结表',
      targetColumn: '编码索引',
      ruleType: 'sequence',
      config: { prefix: 'AM', startFrom: 1 },
      errorMessage: '编码索引必须从AM0001开始严格递增，发现跳号或重复',
    },
    // 总体大纲编码递增验证
    {
      id: 'outline_code_sequence',
      name: '总体大纲编码递增',
      description: '编码索引必须从AM0001开始严格递增，不可跳号或重复',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '总体大纲',
      targetColumn: '编码索引',
      ruleType: 'sequence',
      config: { prefix: 'AM', startFrom: 1 },
      errorMessage: '编码索引必须从AM0001开始严格递增，发现跳号或重复',
    },
    // 总结表编码索引必填验证
    {
      id: 'summary_code_required',
      name: '总结表编码索引必填',
      description: '编码索引不能为空',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '总结表',
      targetColumn: '编码索引',
      ruleType: 'required',
      config: {},
      errorMessage: '编码索引不能为空',
    },
    // 总体大纲编码索引必填验证
    {
      id: 'outline_code_required',
      name: '总体大纲编码索引必填',
      description: '编码索引不能为空',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '总体大纲',
      targetColumn: '编码索引',
      ruleType: 'required',
      config: {},
      errorMessage: '编码索引不能为空',
    },
    // 任务表状态枚举
    {
      id: 'quest_status_enum',
      name: '任务表状态',
      description: '任务状态必须为指定的枚举值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '任务表',
      targetColumn: '状态(Enum Tag)',
      ruleType: 'enum',
      config: { values: ['进行中', '已完成', '已失败', '已放弃'] },
      errorMessage: '状态必须为枚举值之一：进行中、已完成、已失败、已放弃',
    },
    // 任务表类型枚举
    {
      id: 'quest_type_enum',
      name: '任务表类型',
      description: '任务类型必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '任务表',
      targetColumn: '类型',
      ruleType: 'enum',
      config: { values: ['主线', '支线', '日常'] },
      errorMessage: '类型必须为：主线、支线、日常',
    },
    // 任务表优先级枚举
    {
      id: 'quest_priority_enum',
      name: '任务表优先级',
      description: '任务优先级必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '任务表',
      targetColumn: '优先级',
      ruleType: 'enum',
      config: { values: ['紧急', '重要', '普通'] },
      errorMessage: '优先级必须为：紧急、重要、普通',
    },
    // 任务表进度格式
    {
      id: 'quest_progress_format',
      name: '任务表进度',
      description: '进度必须为0%~100%格式',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '任务表',
      targetColumn: '进度（%）',
      ruleType: 'format',
      config: { pattern: '^(100|[1-9]?\\d)%$' },
      errorMessage: '进度必须为0%~100%格式（如：0%、50%、100%）',
    },
    // 装备表状态枚举
    {
      id: 'equip_status_enum',
      name: '装备表状态',
      description: '装备状态必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '装备表',
      targetColumn: '状态',
      ruleType: 'enum',
      config: { values: ['已装备', '闲置'] },
      errorMessage: '状态必须为：已装备、闲置',
    },
    // 装备表品质枚举
    {
      id: 'equip_quality_enum',
      name: '装备表品质',
      description: '装备品质必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '装备表',
      targetColumn: '品质',
      ruleType: 'enum',
      config: { values: ['普通', '优秀', '稀有', '史诗', '传说', '神话', '唯一'] },
      errorMessage: '品质必须为：普通、优秀、稀有、史诗、传说、神话、唯一',
    },
    // 物品表品质枚举
    {
      id: 'item_quality_enum',
      name: '物品表品质',
      description: '物品品质必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '物品表',
      targetColumn: '品质',
      ruleType: 'enum',
      config: { values: ['普通', '优秀', '稀有', '史诗', '传说', '神话', '唯一'] },
      errorMessage: '品质必须为：普通、优秀、稀有、史诗、传说、神话、唯一',
    },
    // 技能表类型枚举
    {
      id: 'skill_type_enum',
      name: '技能表类型',
      description: '技能类型必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '技能表',
      targetColumn: '类型',
      ruleType: 'enum',
      config: { values: ['主动', '被动', '特质'] },
      errorMessage: '类型必须为：主动、被动、特质',
    },
    // 技能表品质枚举
    {
      id: 'skill_quality_enum',
      name: '技能表品质',
      description: '技能品质必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '技能表',
      targetColumn: '品质',
      ruleType: 'enum',
      config: { values: ['普通', '优秀', '稀有', '史诗', '传说', '神话'] },
      errorMessage: '品质必须为：普通、优秀、稀有、史诗、传说、神话',
    },
    // 技能表熟练度数值范围
    {
      id: 'skill_proficiency_range',
      name: '技能熟练度范围',
      description: '技能熟练度必须在 0-100 之间',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '技能表',
      targetColumn: '熟练度',
      ruleType: 'numeric',
      config: { min: 0, max: 100 },
      errorMessage: '熟练度必须在 0-100 之间',
    },
    // 重要人物表在场状态枚举
    {
      id: 'npc_presence_enum',
      name: '重要人物在场状态',
      description: '在场状态必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '重要人物表',
      targetColumn: '在场状态',
      ruleType: 'enum',
      config: { values: ['在场', '离场'] },
      errorMessage: '在场状态必须为：在场、离场',
    },
    // 世界地图点探索状态枚举
    {
      id: 'map_explore_enum',
      name: '地图点探索状态',
      description: '探索状态必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '世界地图点',
      targetColumn: '探索状态',
      ruleType: 'enum',
      config: { values: ['未探索', '部分探索', '已探索'] },
      errorMessage: '探索状态必须为：未探索、部分探索、已探索',
    },
    // 世界地图点重要度枚举
    {
      id: 'map_importance_enum',
      name: '地图点重要度',
      description: '重要度必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '世界地图点',
      targetColumn: '重要度',
      ruleType: 'enum',
      config: { values: ['核心', '重要', '普通'] },
      errorMessage: '重要度必须为：核心、重要、普通',
    },
    // 重要情报重要度枚举
    {
      id: 'intel_importance_enum',
      name: '情报重要度',
      description: '重要度必须为指定值之一',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '重要情报',
      targetColumn: '重要度',
      ruleType: 'enum',
      config: { values: ['核心', '重要', '普通'] },
      errorMessage: '重要度必须为：核心、重要、普通',
    },
    // 主角所在地点关联验证
    {
      id: 'player_location_relation',
      name: '主角地点关联',
      description: '主角所在地点必须存在于世界地图点表',
      enabled: false,
      builtin: true,
      intercept: false,
      targetTable: '主角信息',
      targetColumn: '所在地点',
      ruleType: 'relation',
      config: { refTable: '世界地图点', refColumn: '详细地点' },
      errorMessage: '所在地点必须是世界地图点表中已存在的详细地点',
    },
    // NPC所在地点关联验证
    {
      id: 'npc_location_relation',
      name: 'NPC地点关联',
      description: 'NPC所在地点必须存在于世界地图点表',
      enabled: false,
      builtin: true,
      intercept: false,
      targetTable: '重要人物表',
      targetColumn: '所在地点',
      ruleType: 'relation',
      config: { refTable: '世界地图点', refColumn: '详细地点' },
      errorMessage: '所在地点必须是世界地图点表中已存在的详细地点',
    },
    // 地图元素所在地点关联验证（只允许详细地点，与表格模板保持一致）
    {
      id: 'element_location_relation',
      name: '元素地点关联',
      description: '元素所在地点必须存在于世界地图点表的详细地点',
      enabled: false,
      builtin: true,
      intercept: false,
      targetTable: '地图元素表',
      targetColumn: '所在地点',
      ruleType: 'relation',
      config: { refTable: '世界地图点', refColumn: '详细地点' },
      errorMessage: '所在地点必须是世界地图点表中已存在的详细地点',
    },
    // 全局数据表当前详细地点关联验证
    {
      id: 'global_detail_location_relation',
      name: '全局详细地点关联',
      description: '当前详细地点必须存在于世界地图点表',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '全局数据表',
      targetColumn: '当前详细地点',
      ruleType: 'relation',
      config: { refTable: '世界地图点', refColumn: '详细地点' },
      errorMessage: '当前详细地点必须是世界地图点表中已存在的详细地点',
    },
    // 主角信息表 - 基本属性（键值对，数值型）
    {
      id: 'player_base_attributes_keyvalue',
      name: '主角基本属性',
      description: '基本属性必须为键值对格式，数值范围[0,100]',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '主角信息',
      targetColumn: '基础属性',
      ruleType: 'keyValue',
      config: { valueType: 'numeric', valueMin: 0, valueMax: 100 },
      errorMessage: '基础属性格式必须为"属性名:数值;属性名:数值"，数值范围[0,100]',
    },
    // 主角信息表 - 特有属性（键值对，数值型）
    {
      id: 'player_special_attributes_keyvalue',
      name: '主角特有属性',
      description: '特有属性必须为键值对格式，数值范围[0,100]',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '主角信息',
      targetColumn: '特有属性',
      ruleType: 'keyValue',
      config: { valueType: 'numeric', valueMin: 0, valueMax: 100 },
      errorMessage: '特有属性格式必须为"属性名:数值;属性名:数值"，数值范围[0,100]',
    },
    // 主角信息表 - 人际关系（键值对，文本型）
    {
      id: 'player_relationships_keyvalue',
      name: '主角人际关系',
      description: '人际关系必须为键值对格式',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '主角信息',
      targetColumn: '人际关系',
      ruleType: 'keyValue',
      config: { valueType: 'text' },
      errorMessage: '人际关系格式必须为"角色名:关系词;角色名:关系词"',
    },
    // 重要人物表 - 基本属性（键值对，数值型）
    {
      id: 'npc_base_attributes_keyvalue',
      name: 'NPC基本属性',
      description: '基本属性必须为键值对格式，数值范围[0,100]',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '重要人物表',
      targetColumn: '基础属性',
      ruleType: 'keyValue',
      config: { valueType: 'numeric', valueMin: 0, valueMax: 100 },
      errorMessage: '基础属性格式必须为"属性名:数值;属性名:数值"，数值范围[0,100]',
    },
    // 重要人物表 - 特有属性（键值对，数值型）
    {
      id: 'npc_special_attributes_keyvalue',
      name: 'NPC特有属性',
      description: '特有属性必须为键值对格式，数值范围[0,100]',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '重要人物表',
      targetColumn: '特有属性',
      ruleType: 'keyValue',
      config: { valueType: 'numeric', valueMin: 0, valueMax: 100 },
      errorMessage: '特有属性格式必须为"属性名:数值;属性名:数值"，数值范围[0,100]',
    },
    // 重要人物表 - 人际关系（键值对，文本型）
    {
      id: 'npc_relationships_keyvalue',
      name: 'NPC人际关系',
      description: '人际关系必须为键值对格式',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '重要人物表',
      targetColumn: '人际关系',
      ruleType: 'keyValue',
      config: { valueType: 'text' },
      errorMessage: '人际关系格式必须为"角色名:关系词;角色名:关系词"',
    },
    // 选项表行数限制（有且仅有一行）
    {
      id: 'option_table_single_row',
      name: '选项表单行限制',
      description: '选项表必须有且仅有一行数据',
      enabled: true,
      builtin: true,
      intercept: false,
      targetTable: '选项表',
      targetColumn: null,
      ruleType: 'rowLimit',
      config: { min: 0, max: 1 },
      errorMessage: '选项表必须有且仅有一行数据',
    },
  ];
export {
  STORAGE_KEY_VALIDATION_RULES,
  STORAGE_KEY_VALIDATION_ENABLED,
  STORAGE_KEY_VALIDATION_MODE,
  RULE_TYPE_INFO,
  BUILTIN_VALIDATION_RULES,
};
