export type GachaRarity = '普通' | '优秀' | '稀有' | '史诗' | '传说' | '神话';

export type GachaPoolTag = string;

export type GachaRewardTarget = 'inventory' | 'equipment';

export interface GachaPoolDefinition {
  id: GachaPoolTag;
  name: string;
  builtin: boolean;
  visibleInTabs: boolean;
  includeInAll: boolean;
  order: number;
}

export interface GachaItemDefinition {
  id: string;
  name: string;
  type: string;
  quality: GachaRarity;
  description: string;
  poolTags: readonly GachaPoolTag[];
  icon?: string;
  iconUrl?: string;
  localIconKey?: string;
  enabled?: boolean;
  order?: number;
  createdAt?: number;
  updatedAt?: number;
  weight: number;
  stackable: boolean;
  unique: boolean;
  grantQuantity: number;
  rewardTarget: GachaRewardTarget;
}

export const GACHA_CATALOG_EXPORT_KIND = 'acu-gacha-items';

export const GACHA_CATALOG_VERSION = 1;

export const FORTUNE_CURRENCY_NAME = '骰运';

export const BUILTIN_GACHA_POOL_DEFINITIONS: readonly GachaPoolDefinition[] = [
  { id: '全部', name: '全部', builtin: true, visibleInTabs: true, includeInAll: false, order: 0 },
  { id: '奇幻', name: '奇幻', builtin: true, visibleInTabs: true, includeInAll: true, order: 10 },
  { id: '修真', name: '修真', builtin: true, visibleInTabs: true, includeInAll: true, order: 20 },
  { id: '都市', name: '都市', builtin: true, visibleInTabs: true, includeInAll: true, order: 30 },
  { id: '校园', name: '校园', builtin: true, visibleInTabs: true, includeInAll: true, order: 40 },
  { id: '历史', name: '历史', builtin: true, visibleInTabs: true, includeInAll: true, order: 50 },
];

export const GACHA_POOL_TAGS: readonly GachaPoolTag[] = BUILTIN_GACHA_POOL_DEFINITIONS.map(pool => pool.id);

export const GACHA_RARITY_ORDER: readonly GachaRarity[] = ['普通', '优秀', '稀有', '史诗', '传说', '神话'];

export const GACHA_REWARD_TARGETS: readonly GachaRewardTarget[] = ['inventory', 'equipment'];

export const GACHA_DRAW_COST_SINGLE = 10;

export const GACHA_DRAW_COST_TEN = 90;

export const GACHA_MESSAGE_REWARD = 1;

export const GACHA_CHECK_REWARD = 1;

export const GACHA_CHARS_PER_FORTUNE = 20;

export const GACHA_ACTIVE_SECONDS_PER_FORTUNE = 10;

export const GACHA_RARE_PITY_THRESHOLD = 10;

export const GACHA_LEGEND_PITY_THRESHOLD = 50;

export const GACHA_ACTIVE_WINDOW_MS = 3 * 60 * 1000;

export const GACHA_ACTIVE_HEARTBEAT_MS = 1000;

export const GACHA_RECENT_REWARD_LIMIT = 12;

export const GACHA_SHARD_VALUES: Record<GachaRarity, number> = {
  普通: 1,
  优秀: 3,
  稀有: 8,
  史诗: 20,
  传说: 50,
  神话: 120,
};

export const GACHA_RARITY_WEIGHTS: Record<GachaRarity, number> = {
  普通: 55,
  优秀: 25,
  稀有: 12,
  史诗: 5,
  传说: 2.5,
  神话: 0.5,
};

/**
 * Gacha item 设计理念：
 * - 物品首先要服务角色扮演。争取提供给玩家一个可立刻展开的场景、麻烦、欲望或选择。
 * - 尽量让每件物品都有鲜明效果，并且有利有弊：好处推动行动，代价制造戏剧，避免只写成单纯的强化道具。
 * - 鼓励引用神话、文学、游戏、影视、都市传说、历史典故或流行梗作为出处/原作灵感，让抽到物品本身就有趣。
 * - 有出处的物品应保持“灵感致敬”而非大段复刻；用一句描述点出气质、用途和风险即可。
 * - 稀有度越高，效果越应该改变局面或带来强烈叙事钩子；低稀有度也应有小而具体的玩法。
 * - 描述优先写可被 AI 和玩家使用的效果文本，例如“可以……但……”“使用后……同时……”。
 * - 物品需要能自然落入当前池子主题：奇幻、修真、都市、校园、历史可以交叉，但不要只靠名字贴标签。
 */
export const GACHA_ITEM_DEFINITIONS: readonly GachaItemDefinition[] = [
  {
    id: 'urban_cola_bottle_caps',
    name: '可乐瓶盖儿',
    type: '材料',
    quality: '普通',
    description: '可作为通用货币使用的金属瓶盖，价值不菲，适合交易、贿赂或支付报酬。',
    poolTags: ['都市'],
    weight: 1.6,
    stackable: true,
    unique: false,
    grantQuantity: 12,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_shenbao_tonic',
    name: '肾宝',
    type: '消耗品',
    quality: '普通',
    description:
      '可疑的补品。广告词：男人要肾好，就要喝肾宝，喝了以后比刘翔快，比姚明高，一瓶提神醒脑，两瓶永不疲劳，三瓶长生不老。',
    poolTags: ['都市'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_penguin_bandage',
    name: '企鹅创口贴',
    type: '消耗品',
    quality: '普通',
    description: '画着企鹅图案的可爱创口贴，可用于处理小伤口，止血和保护伤处。',
    poolTags: ['校园', '都市'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 5,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_red_dragon_tile',
    name: '红中',
    type: '道具',
    quality: '普通',
    description: '一张红中麻将牌。使用后可说出一个让目标深信不疑的谎话，每张只能使用一次。',
    poolTags: ['校园', '都市'],
    weight: 1.3,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'all_plot_coupon',
    name: '剧情优惠券',
    type: '消耗品',
    quality: '普通',
    description: '一次性凭证。使用后可获得一条与当前目标有关的模糊线索，用后销毁。',
    poolTags: ['奇幻', '修真', '都市', '校园', '历史'],
    weight: 1.8,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_mushroom_growth',
    name: '变大蘑菇',
    type: '消耗品',
    quality: '优秀',
    description: '红白色蘑菇。食用后体型临时变大，持续时间较短，效果结束后恢复原状。',
    poolTags: ['奇幻', '校园'],
    weight: 1.2,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_obedience_water',
    name: '听话水',
    type: '消耗品',
    quality: '优秀',
    description: '无色药水。饮用者短时间内会服从使用者的简单命令，直到药效消失。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_bamboo_copter',
    name: '竹蜻蜓',
    type: '道具',
    quality: '优秀',
    description: '佩戴在头顶的小型飞行器，可进行低空飞行，速度较慢，强风环境下不稳定。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_silver_scale_breastplate',
    name: '银鳞胸甲',
    type: '装备',
    quality: '优秀',
    description: '银鳞胸甲，5金一件。',
    poolTags: ['奇幻'],
    weight: 1.2,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'urban_physics_holy_crowbar',
    name: '物理学圣剑',
    type: '装备',
    quality: '稀有',
    description: '一根坚固的撬棍，可用于撬门、破坏木箱、近战格斗和简易杠杆操作。',
    poolTags: ['都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_dark_ring',
    name: '黑暗之环',
    type: '装备',
    quality: '史诗',
    description: '佩戴者胸口会出现一个巨大的黑暗之环。佩戴者死亡后可在最近的安全地点苏醒一次。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_soul_gem',
    name: '灵魂宝石',
    type: '道具',
    quality: '史诗',
    description:
      '可以寄居少女灵魂的宝石，灵魂可以通过灵魂宝石来操控自己的肉体进行战斗，并且用魔法来修复自己所受到的损伤。灵魂宝石需要定期用悲叹之种来进行净化，否则每次使用魔力，或随着时间流逝，灵魂宝石会逐步污浊，最终导致其内的灵魂失去理智，沦为魔女。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_anywhere_door',
    name: '任意门',
    type: '道具',
    quality: '传说',
    description: '粉色传送门。说出目的地后打开，可让少量人员通过，单次开启时间有限。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_twin_blades_of_azzinoth',
    name: '埃辛诺斯战刃',
    type: '装备',
    quality: '传说',
    description: '一对弯月形战刃，适合高速近战。双持时威力更强，但对使用者负担很大。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_ashbringer',
    name: '灰烬使者',
    type: '装备',
    quality: '传说',
    description: '圣光属性双手剑，对亡灵、诅咒和黑暗力量有额外效果。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_elder_wand',
    name: '老魔杖',
    type: '装备',
    quality: '传说',
    description:
      '极强的魔杖，施法威力显著提高，但所有权会随击败或缴械关系转移。使用时会引来追求强大魔法力量的巫师的觊觎。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_invisibility_cloak',
    name: '隐身衣',
    type: '装备',
    quality: '传说',
    description: '可覆盖身体的斗篷，穿戴后隐去外形，但声音、气味和触碰仍会暴露位置。',
    poolTags: ['奇幻', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_excalibur',
    name: '石中剑',
    type: '装备',
    quality: '传说',
    description: '传说中的王权之剑，只有被认可者能拔出。可作为统治权或骑士资格象征。',
    poolTags: ['奇幻', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_purple_gold_gourd',
    name: '紫金葫芦',
    type: '道具',
    quality: '传说',
    description: '对准目标呼唤其真实姓名，若目标答应，会被缩小并困入葫芦；同时只能困住一人。',
    poolTags: ['修真', '历史', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_fengyue_baojian',
    name: '风月宝鉴',
    type: '道具',
    quality: '传说',
    description: '双面古镜。照正面时会显示满足使用者内心色欲的幻象，照背面时得见红粉骷髅，大幅度抑制情欲',
    poolTags: ['历史', '修真'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_wishing_phone_booth',
    name: '如意电话亭',
    type: '道具',
    quality: '神话',
    description: '可拨打愿望电话的亭子。许出的愿望会在走出电话亭时以不容置疑的方式真切地变为现实，使用一次会自动销毁。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_death_note',
    name: '死亡笔记',
    type: '道具',
    quality: '神话',
    description: '黑色笔记本。写下真实姓名和死因后目标会死亡；每次使用都会留下可追查痕迹。',
    poolTags: ['都市', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_thunderfury',
    name: '雷霆之怒，逐风者的祝福之剑',
    type: '装备',
    quality: '神话',
    description: '风暴属性传说长剑，可召唤雷电和强风。使用时会明显暴露持有者位置。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_philosophers_stone',
    name: '哲人石',
    type: '道具',
    quality: '神话',
    description: '炼金圣物，可进行物质转化并制造延寿药剂，使用条件苛刻。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_jingu_bang',
    name: '金箍棒',
    type: '装备',
    quality: '神话',
    description: '可随心伸缩和改变重量的神兵，适合近战、支撑、破坏和压制大型目标。',
    poolTags: ['修真', '奇幻', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_heaven_bottle',
    name: '掌天瓶',
    type: '道具',
    quality: '神话',
    description: '神秘小瓶，可催熟灵药或积蓄特殊灵液。每次使用需要等待较长恢复时间。',
    poolTags: ['修真'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_shining_trapezohedron',
    name: '闪耀的偏方三八面体',
    type: '道具',
    quality: '神话',
    description: '多面体黑石，凝视后可获得隐秘知识，但会引来未知存在的注意。',
    poolTags: ['历史', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_necronomicon',
    name: '死灵之书',
    type: '道具',
    quality: '神话',
    description: '记载禁忌知识的古书。阅读可获得仪式或神秘学信息，但会造成精神损耗。',
    poolTags: ['历史', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_flame_mantra',
    name: '焚决',
    type: '功法',
    quality: '神话',
    description: '可吞噬异火并进化的修炼功法。每吞噬一种强火源可提升阶位，失败会造成严重反噬。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_coin_railgun',
    name: '超电磁炮',
    type: '装备',
    quality: '传说',
    description: '以硬币等金属弹丸为介质发射高速电磁弹。每次发射消耗一枚金属弹丸和大量电力。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'school_revue_stage_device',
    name: '舞台装置',
    type: '道具',
    quality: '史诗',
    description: '可展开一座临时舞台，限定范围内的行动会被转化为表演、竞演或决斗形式。每天一次。',
    poolTags: ['校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_at_field',
    name: 'AT立场',
    type: '道具',
    quality: '神话',
    description: '展开绝对领域，可抵挡一次大多数常规攻击；同类力场或精神干涉可削弱它。',
    poolTags: ['奇幻', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_rtx_5090',
    name: 'RTX 5090',
    type: '道具',
    quality: '传说',
    description: '高端显卡，具备强大的图形和 AI 计算能力。运行时耗电和发热很高，需要稳定供电。',
    poolTags: ['都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'all_jinkela_fertilizer',
    name: '金坷垃',
    type: '材料',
    quality: '优秀',
    description: '肥料添加剂，可显著提高一片小型农田或盆栽的作物长势。每包只能使用一次。',
    poolTags: ['都市', '校园', '历史', '修真'],
    weight: 1.2,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_white_album',
    name: '白色相簿',
    type: '道具',
    quality: '优秀',
    description: '白色封面的普通相簿，可保存照片、票根和手写便签，没有特殊能力。',
    poolTags: ['校园', '都市'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_computer_parts_package',
    name: '电脑配件',
    type: '任务物品',
    quality: '稀有',
    description: '标注为电脑配件的密封包裹，内含催情用媚药。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_sword_of_benevolence',
    name: '仁之剑',
    type: '装备',
    quality: '史诗',
    description:
      '刘备的双剑之一。单独使用为轻剑；与义之剑同时装备时，可提升防守和统率类行动。当持有者违背仁义之道时，失去所有能力。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'history_sword_of_righteousness',
    name: '义之剑',
    type: '装备',
    quality: '史诗',
    description:
      '刘备的双剑之一。单独使用为轻剑；与仁之剑同时装备时，可提升支援和结盟类行动。当持有者违背仁义之道时，失去所有能力。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'history_imperial_jade_seal',
    name: '传国玉玺',
    type: '道具',
    quality: '神话',
    description: '以和氏璧雕琢而成的玉玺，可证明在中华地区绝对的天命与统治正当性，无价之宝。展示时会引来争夺和追索。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_iron_certificate',
    name: '丹书铁券',
    type: '任务物品',
    quality: '传说',
    description: '刻有誓文的免罪凭证，可抵免一次重罪或死罪指控；对谋反等特例未必有效。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_sunflower_manual',
    name: '葵花宝典',
    type: '功法',
    quality: '神话',
    description: '自宫之后才可学习的高深武学秘籍，可显著提升速度、身法和细密招式修为。',
    poolTags: ['修真', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_eighty_nine_mystic_art',
    name: '八九玄功',
    type: '功法',
    quality: '神话',
    description: '玄门护身变化之法，可强化肉身并进行多种变化。变化越复杂，消耗越大。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_huntian_sash',
    name: '混天绫',
    type: '装备',
    quality: '传说',
    description: '红色仙绫，可缠缚目标、牵引物体或在水火中护身。对强力目标需要持续操控。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_qiankun_ring',
    name: '乾坤圈',
    type: '装备',
    quality: '传说',
    description: '金色法圈，可投掷打击、收回护身或压制妖邪。离手后需要召回才能再次使用。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_jade_purification_vase',
    name: '玉净瓶',
    type: '道具',
    quality: '神话',
    description: '白玉宝瓶，可盛放灵水并收纳小型目标。瓶内空间有限，强行收纳会快速消耗灵力。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_nine_tooth_rake',
    name: '九齿钉耙',
    type: '装备',
    quality: '传说',
    description: '九齿重兵器，适合破甲、钩拽和大范围横扫。重量很高，使用者需要足够力量。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_white_dragon_horse',
    name: '白龙马',
    type: '坐骑',
    quality: '神话',
    description: '可化为白马的龙族坐骑，能长途跋涉、涉水渡险。受重伤后需以龙形休养。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_raw_melon',
    name: '生瓜蛋子',
    type: '消耗品',
    quality: '普通',
    description: '未熟透的瓜，口感生涩。',
    poolTags: ['都市'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_water_warding_pearl',
    name: '避水珠',
    type: '道具',
    quality: '稀有',
    description: '通透圆润的宝珠，贴身携带可在水下短暂呼吸并避开普通水压。遇到灵潮或深海暗流时效果会减弱。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_herbal_milk_tea',
    name: '中药奶茶',
    type: '消耗品',
    quality: '普通',
    description: '带有中药味儿的奶茶，味道一言难尽，让人认真思考餐饮创新的边界。',
    poolTags: ['都市', '校园'],
    weight: 1.3,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_hypnosis_app',
    name: '催眠APP',
    type: '道具',
    quality: '史诗',
    description:
      '不知为何突然出现在手机上的界面简陋的手机应用，将催眠APP的画面展示给智慧生物时可以施加强力的催眠效果。生效时间与同时作用人数有限，且催眠效果取决于催眠内容与对方自我认识与尝试的乖离程度。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_scallion_pancake',
    name: '葱油饼',
    type: '消耗品',
    quality: '普通',
    description: '外酥内软、葱香浓郁的热饼，食用后少量恢复体力，也适合在路边快速充饥。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_zhajiang_noodles',
    name: '炸酱面',
    type: '消耗品',
    quality: '普通',
    description: '酱香浓厚的一碗面，食用后恢复少量体力和心情，吃完容易想再来一碗。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fairy_crystal_slipper',
    name: '水晶鞋',
    type: '道具',
    quality: '史诗',
    description:
      '透明精致的鞋子，穿上后会显著提升礼仪、舞蹈和第一印象。第一次穿着的当晚12点前有效，之后魔力消失，鞋子会留在原地。',
    poolTags: ['奇幻', '校园', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fairy_poisoned_apple',
    name: '毒苹果',
    type: '消耗品',
    quality: '稀有',
    description: '鲜红的苹果。食用者会陷入近似死亡的沉睡，期间外伤和疾病不会继续恶化。只能使用一次。',
    poolTags: ['奇幻', '历史'],
    weight: 1.1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fairy_little_match',
    name: '火柴',
    type: '材料',
    quality: '普通',
    description: '普通火柴，可以点火、照明或生火。受潮后可能无法使用。',
    poolTags: ['奇幻', '校园', '历史', '都市'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 8,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_raccoon_crispy_noodles',
    name: '小浣熊干脆面',
    type: '消耗品',
    quality: '普通',
    description: '童年味道的干脆面，捏碎后更香。食用后少量恢复体力和心情。',
    poolTags: ['都市', '校园'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_strawberry_milk',
    name: '草莓牛奶',
    type: '消耗品',
    quality: '普通',
    description: '粉色纸盒装饮品，甜味很足。饮用后少量恢复精神。',
    poolTags: ['都市', '校园'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_flashlight',
    name: '手电筒',
    type: '道具',
    quality: '普通',
    description: '便携照明工具，可照亮黑暗区域。电量不足时光线会变弱。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.3,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_membership_card',
    name: '会员卡',
    type: '道具',
    quality: '稀有',
    description: '任何消费都能五折，但持有者卖出物品时价格也会五折。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_stebaker_car',
    name: '斯蒂庞克牌汽车',
    type: '道具',
    quality: '史诗',
    description: '老派轿车，开上街极其显眼，是身份的象征。',
    poolTags: ['历史', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_golden_buddha_throne',
    name: '玉座金佛',
    type: '任务物品',
    quality: '传说',
    description: '贵重佛像，应该归属于值得的人。',
    poolTags: ['历史', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_red_pill',
    name: '红色药丸',
    type: '消耗品',
    quality: '传说',
    description: '一旦吞下，即可看见隐藏在日常背后的真实。此举无法撤回。',
    poolTags: ['都市', '奇幻'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_blue_pill',
    name: '蓝色药丸',
    type: '消耗品',
    quality: '稀有',
    description: '吞下后可忘记一切异常，回归到安稳的日常。',
    poolTags: ['都市', '奇幻'],
    weight: 1.1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_memory_bread',
    name: '记忆面包',
    type: '消耗品',
    quality: '史诗',
    description: '把文字印在面包上吃下即可记住内容，消化后效果可能消退。',
    poolTags: ['校园', '都市'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'all_regret_medicine',
    name: '后悔药',
    type: '消耗品',
    quality: '神话',
    description: '一次性药丸，可让故事回溯到某个节点之前。只能使用一次。',
    poolTags: ['奇幻', '修真', '都市', '校园', '历史'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_voice_recorder',
    name: '录音笔',
    type: '道具',
    quality: '优秀',
    description: '可长时间录音并保存证据。嘈杂环境下需要贴近声源。',
    poolTags: ['都市', '校园'],
    weight: 1.2,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_devil_passport',
    name: '恶魔护照',
    type: '道具',
    quality: '神话',
    description: '出示后可让对方允许或原谅持有者的任何行为。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_maliang_brush',
    name: '马良的笔',
    type: '道具',
    quality: '神话',
    description: '神奇画笔，画出的事物可能化为现实。',
    poolTags: ['奇幻', '历史', '修真'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_master_key',
    name: '万能钥匙',
    type: '道具',
    quality: '传说',
    description: '可尝试打开几乎任何锁。越复杂的封印越需要时间和代价。',
    poolTags: ['都市', '校园', '奇幻', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_allezuhod_pen',
    name: '0-08 阿勒苏霍德之笔',
    type: '道具',
    quality: '神话',
    description: '用这支笔写下的故事一定会成真，但是总会以离奇并讽刺的方式来反噬它的主人。',
    poolTags: ['奇幻', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_shrink_ray',
    name: '缩小灯',
    type: '道具',
    quality: '传说',
    description: '照射目标可使其缩小，持续时间和缩小比例取决于电量。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_voice_changer_bowtie',
    name: '变声器',
    type: '道具',
    quality: '史诗',
    description: '蝴蝶结外观的变声器，可模拟他人声音。需要先听过目标声线。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_anesthetic_needle_watch',
    name: '麻醉针',
    type: '道具',
    quality: '史诗',
    description: '蝴蝶结机关发射的麻醉针，可让目标短暂昏睡。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_golden_toilet',
    name: '黄金马桶',
    type: '道具',
    quality: '神话',
    description: '被戏称为黄金马桶的宏伟王座，能维持一片摇摇欲坠的帝国幻象，但会极度消耗持有者。区区凡人请勿久坐。',
    poolTags: ['奇幻', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_molotov_cocktail',
    name: '燃烧瓶',
    type: '消耗品',
    quality: '优秀',
    description: '危险的投掷物，命中后会制造短暂火焰和烟雾。使用不当很容易伤到自己或引发更大麻烦。',
    poolTags: ['都市', '历史'],
    weight: 1.1,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_handgun',
    name: '手枪',
    type: '装备',
    quality: '稀有',
    description: '常见小型枪械，可用于威慑和短距离自卫。弹药有限，开火会立刻引来注意。',
    poolTags: ['都市', '历史'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'urban_wheelchair',
    name: '轮椅',
    type: '道具',
    quality: '普通',
    description: '结实的可折叠轮椅，可协助行动不便者移动，也能临时搬运伤员或少量物资。在轮椅上开枪时容易误伤队友。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.2,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_mantou_slice_er',
    name: '馒头片儿',
    type: '消耗品',
    quality: '普通',
    description: '烤得焦香的馒头片儿，客栈中的常见小食。等待制作的过程十分煎熬。',
    poolTags: ['历史', '都市'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_mantou',
    name: '馒头',
    type: '消耗品',
    quality: '普通',
    description: '白胖朴实的馒头，能快速充饥，搭配咸菜或汤水效果更好。',
    poolTags: ['历史', '都市', '修真'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 4,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_white_gloves',
    name: '白手套',
    type: '装备',
    quality: '优秀',
    description: '一副干净得过分的白手套，适合在不留下指纹的情况下进行精细操作。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'urban_black_gloves',
    name: '黑手套',
    type: '装备',
    quality: '优秀',
    description: '一副贴合手型的黑色手套，适合潜入、伪装和夜间行动，握持工具时也更加稳当。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1.1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'school_yellow_duck',
    name: '小黄鸭',
    type: '道具',
    quality: '普通',
    description: '捏起来会发出轻响的黄色小鸭玩具。能缓和紧张气氛，也能在水面上当作醒目的小标记。',
    poolTags: ['校园', '都市'],
    weight: 1.3,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_thermos',
    name: '暖水瓶',
    type: '道具',
    quality: '普通',
    description: '保温效果不错的暖水瓶，可携带热水、药汤或临时需要保温的液体，外壳经不起剧烈碰撞。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.2,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_piggy_bank',
    name: '猪猪存钱罐',
    type: '道具',
    quality: '稀有',
    description: '神奇的存钱罐。每过一段时间内部的财富会一点点增加。',
    poolTags: ['都市', '校园'],
    weight: 0.9,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_felix_felicis',
    name: '福灵剂',
    type: '消耗品',
    quality: '传说',
    description: '短时间内极大程度上使人变得幸运药剂，几乎可以心想事成。药效结束后的一段时间会变得极为不幸。',
    poolTags: ['奇幻', '校园'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_estus_flask',
    name: '原素瓶',
    type: '道具',
    quality: '史诗',
    description: '橙色小瓶。饮用可以恢复伤势或精神。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_scroll_of_town_portal',
    name: '回城卷轴',
    type: '消耗品',
    quality: '优秀',
    description: '展开并完成短暂吟唱后可回到特定据点；吟唱期间被打断会浪费卷轴并暴露坐标。',
    poolTags: ['奇幻', '修真', '历史'],
    weight: 1.2,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_forget_sorrow_water',
    name: '忘忧水',
    type: '消耗品',
    quality: '稀有',
    description: '一杯清甜无味的水。饮下可忘记一段与悲伤、恐惧或执念相关的重要记忆。',
    poolTags: ['修真', '都市', '历史'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_mengpo_soup',
    name: '孟婆汤',
    type: '消耗品',
    quality: '传说',
    description: '奈何桥边的忘川汤。饮下可彻底斩断旧怨、诅咒或精神污染，也会抹去所有珍贵关系与身份链接。',
    poolTags: ['修真', '历史', '奇幻'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_elixir_of_immortality',
    name: '长生不老药',
    type: '消耗品',
    quality: '神话',
    description: '帝王方士梦寐以求的丹药。服下可停止衰老并抵抗常规疾病，但不会免除痛苦、封印或厄运，还会引来所有觊觎长生者。',
    poolTags: ['修真', '历史', '奇幻'],
    weight: 1,
    stackable: true,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_portal_gun',
    name: '传送枪',
    type: '道具',
    quality: '神话',
    description: '手持设备，可在合适平面上制造两扇相连传送门，动量会被保留，电量、角度和落点错误都可能造成灾难。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_bigu_dan',
    name: '辟谷丹',
    type: '消耗品',
    quality: '普通',
    description: '修行者常备丹丸。服下一粒可数日不饥不渴，但口中会残留草木苦味，期间对宴饮、香气和烟火气格外迟钝。',
    poolTags: ['修真', '历史'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_pencil_case',
    name: '铅笔盒',
    type: '道具',
    quality: '普通',
    description: '装着铅笔、橡皮和尺子的铅笔盒。除了书写和画图，也适合收纳细小零件或临时藏下一张纸条。',
    poolTags: ['校园', '都市'],
    weight: 1.4,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_time_machine',
    name: '时光机',
    type: '道具',
    quality: '神话',
    description: '可尝试前往过去或未来的机器，每次启动都可能制造时间偏差或分支，冷却时间很长。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
];
