export type GachaRarity = '普通' | '优秀' | '稀有' | '史诗' | '传说' | '神话' | '唯一';

export type GachaPoolTag = string;

export type GachaRewardTarget = 'inventory' | 'equipment';

export type GachaCustomFields = Record<string, string>;

export type GachaRewardTargetColumnKey =
  | 'name'
  | 'type'
  | 'quantity'
  | 'quality'
  | 'tags'
  | 'effect'
  | 'description'
  | 'part'
  | 'status';

export type GachaRewardTargetColumns = Partial<Record<GachaRewardTargetColumnKey, string>>;

export interface GachaPoolDefinition {
  id: GachaPoolTag;
  name: string;
  builtin: boolean;
  visibleInTabs: boolean;
  includeInAll: boolean;
  order: number;
}

export interface GachaItemDefinition {
  id: string;
  name: string;
  type: string;
  quality: GachaRarity;
  /** 标签：用于详情副标题「类型 · 品质 · 标签 · 数量X」与物品表「标签」列 */
  tags?: string;
  /** 效果：详情正文第一行，对应物品/装备表「效果」列 */
  effect?: string;
  description: string;
  poolTags: readonly GachaPoolTag[];
  icon?: string;
  customFields?: GachaCustomFields;
  enabled?: boolean;
  order?: number;
  createdAt?: number;
  updatedAt?: number;
  weight: number;
  stackable: boolean;
  unique: boolean;
  grantQuantity: number;
  rewardTarget: GachaRewardTarget;
  targetTable?: string;
  targetColumns?: GachaRewardTargetColumns;
}

export const GACHA_CATALOG_EXPORT_KIND = 'acu-gacha-items';

export const GACHA_CATALOG_VERSION = 2;

export const FORTUNE_CURRENCY_NAME = '骰运';

export const BUILTIN_GACHA_POOL_DEFINITIONS: readonly GachaPoolDefinition[] = [
  { id: '全部', name: '全部', builtin: true, visibleInTabs: true, includeInAll: false, order: 0 },
  { id: '奇幻', name: '奇幻', builtin: true, visibleInTabs: true, includeInAll: true, order: 10 },
  { id: '修真', name: '修真', builtin: true, visibleInTabs: true, includeInAll: true, order: 20 },
  { id: '都市', name: '都市', builtin: true, visibleInTabs: true, includeInAll: true, order: 30 },
  { id: '校园', name: '校园', builtin: true, visibleInTabs: true, includeInAll: true, order: 40 },
  { id: '历史', name: '历史', builtin: true, visibleInTabs: true, includeInAll: true, order: 50 },
];

export const GACHA_POOL_TAGS: readonly GachaPoolTag[] = BUILTIN_GACHA_POOL_DEFINITIONS.map(pool => pool.id);

export const GACHA_RARITY_ORDER: readonly GachaRarity[] = ['普通', '优秀', '稀有', '史诗', '传说', '神话', '唯一'];

/** 品质为“唯一”时，物品自动按唯一物品处理（不再使用独立的唯一复选框） */
export const GACHA_UNIQUE_RARITY: GachaRarity = '唯一';

export const GACHA_REWARD_TARGETS: readonly GachaRewardTarget[] = ['inventory', 'equipment'];

export const GACHA_DRAW_COST_SINGLE = 10;

export const GACHA_DRAW_COST_TEN = 90;

export const GACHA_MESSAGE_REWARD = 1;

export const GACHA_CHECK_REWARD = 1;

export const GACHA_CHARS_PER_FORTUNE = 20;

export const GACHA_ACTIVE_SECONDS_PER_FORTUNE = 10;

export const GACHA_RARE_PITY_THRESHOLD = 10;

export const GACHA_LEGEND_PITY_THRESHOLD = 50;

export const GACHA_ACTIVE_WINDOW_MS = 3 * 60 * 1000;

export const GACHA_ACTIVE_HEARTBEAT_MS = 1000;

export const GACHA_RECENT_REWARD_LIMIT = 12;

export const GACHA_SHARD_VALUES: Record<GachaRarity, number> = {
  普通: 1,
  优秀: 3,
  稀有: 8,
  史诗: 20,
  传说: 50,
  神话: 120,
  唯一: 200,
};

export const GACHA_RARITY_WEIGHTS: Record<GachaRarity, number> = {
  普通: 55,
  优秀: 25,
  稀有: 12,
  史诗: 5,
  传说: 2.5,
  神话: 0.5,
  唯一: 0.2,
};

/**
 * Gacha item 设计理念：
 * - 物品首先要服务角色扮演。争取提供给玩家一个可立刻展开的场景、麻烦、欲望或选择。
 * - 尽量让每件物品都有鲜明效果，并且有利有弊：好处推动行动，代价制造戏剧，避免只写成单纯的强化道具。
 * - 鼓励引用神话、文学、游戏、影视、都市传说、历史典故或流行梗作为出处/原作灵感，让抽到物品本身就有趣。
 * - 有出处的物品应保持“灵感致敬”而非大段复刻；用一句描述点出气质、用途和风险即可。
 * - 稀有度越高，效果越应该改变局面或带来强烈叙事钩子；低稀有度也应有小而具体的玩法。
 * - 描述优先写可被 AI 和玩家使用的效果文本，例如“可以……但……”“使用后……同时……”。
 * - 物品需要能自然落入当前池子主题：奇幻、修真、都市、校园、历史可以交叉，但不要只靠名字贴标签。
 */
export const GACHA_ITEM_DEFINITIONS: readonly GachaItemDefinition[] = [
  {
    id: 'urban_cola_bottle_caps',
    name: '可乐瓶盖儿',
    type: '材料',
    quality: '普通',
    tags: '[货币][金属][都市]',
    effect: '可作为通用货币直接用于交易、贿赂或支付报酬，重量轻便、不易伪造。',
    description: '可作为通用货币使用的金属瓶盖，价值不菲，适合交易、贿赂或支付报酬。',
    poolTags: ['都市'],
    weight: 1.6,
    stackable: true,
    unique: false,
    grantQuantity: 12,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_shenbao_tonic',
    name: '肾宝',
    type: '消耗品',
    quality: '普通',
    tags: '[恢复][可疑][都市]',
    effect: '饮用后提神醒脑、缓解疲劳，恢复少量体力与精神；但药效不稳，可能附带头晕、心悸或尴尬的副作用。',
    description: '可疑补品，号称提神醒脑、缓解疲劳，效果和副作用都不太可靠。',
    poolTags: ['都市'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_penguin_bandage',
    name: '企鹅创口贴',
    type: '消耗品',
    quality: '普通',
    tags: '[恢复][可爱][校园]',
    effect: '贴在伤口上可快速止血并保护伤处，促进小伤口愈合；可爱的企鹅图案还能小小安抚心情。',
    description: '画着企鹅图案的可爱创口贴，可用于处理小伤口，止血和保护伤处。',
    poolTags: ['校园', '都市'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 5,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_red_dragon_tile',
    name: '红中',
    type: '道具',
    quality: '普通',
    tags: '[唬骗][一次性][校园]',
    effect: '使用后可说出一个让目标深信不疑的谎话，越贴近其既有认知越难被识破；每张只能使用一次。',
    description: '一张红中麻将牌。使用后可说出一个让目标深信不疑的谎话，每张只能使用一次。',
    poolTags: ['校园', '都市'],
    weight: 1.3,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'all_plot_coupon',
    name: '剧情优惠券',
    type: '消耗品',
    quality: '普通',
    tags: '[线索][一次性][万能]',
    effect: '使用后获得一条与当前目标有关的模糊线索，线索方向随机但必然相关，用后销毁。',
    description: '一次性凭证。使用后可获得一条与当前目标有关的模糊线索，用后销毁。',
    poolTags: ['奇幻', '修真', '都市', '校园', '历史'],
    weight: 1.8,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_mushroom_growth',
    name: '变大蘑菇',
    type: '消耗品',
    quality: '优秀',
    tags: '[变身][短效][奇幻]',
    effect: '食用后体型临时变大一号，力量与体型相关判定获得优势；持续时间较短，效果结束后恢复原状，期间可能撑坏衣物。',
    description: '红白色蘑菇。食用后体型临时变大，持续时间较短，效果结束后恢复原状。',
    poolTags: ['奇幻', '校园'],
    weight: 1.2,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_obedience_water',
    name: '听话水',
    type: '消耗品',
    quality: '优秀',
    tags: '[支配][短效][禁忌]',
    effect: '饮用者短时间内会服从使用者的简单命令，直到药效消失；意志坚定者可能抵抗，事后可能留下记忆缺口与道德风险。',
    description: '无色药水。饮用者短时间内会服从使用者的简单命令，直到药效消失。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_bamboo_copter',
    name: '竹蜻蜓',
    type: '道具',
    quality: '优秀',
    tags: '[飞行][便携][都市]',
    effect: '佩戴在头顶即可低空飞行，速度较慢、机动灵活；强风或恶劣天气下不稳定，长时间飞行会耗尽电力。',
    description: '佩戴在头顶的小型飞行器，可进行低空飞行，速度较慢，强风环境下不稳定。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_silver_scale_breastplate',
    name: '银鳞胸甲',
    type: '护具',
    quality: '优秀',
    tags: '[护甲][轻便][奇幻]',
    effect: '穿戴后提供可靠的物理防护，银鳞对毒素与腐蚀也有一定抗性；重量较轻，不影响灵活行动。',
    description: '银鳞胸甲，5金一件。',
    poolTags: ['奇幻'],
    weight: 1.2,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'urban_physics_holy_crowbar',
    name: '物理学圣剑',
    type: '武器',
    quality: '稀有',
    tags: '[近战][撬锁][工具]',
    effect: '坚固撬棍，可用于撬门、破拆木箱、近战格斗与简易杠杆操作；物理意义上的万能钥匙。',
    description: '一根坚固的撬棍，可用于撬门、破坏木箱、近战格斗和简易杠杆操作。',
    poolTags: ['都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_dark_ring',
    name: '黑暗之环',
    type: '饰品',
    quality: '史诗',
    tags: '[复活][诅咒][奇幻]',
    effect: '佩戴者死亡后可在最近的安全地点苏醒一次；苏醒时胸口浮现巨大的黑暗之环，代价是失去所有非绑定的随身财物。',
    description: '佩戴者胸口会出现一个巨大的黑暗之环。佩戴者死亡后可在最近的安全地点苏醒一次。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_soul_gem',
    name: '灵魂宝石',
    type: '道具',
    quality: '史诗',
    tags: '[施法][治疗][契约]',
    effect: '寄宿灵魂的宝石，可辅助施法、修复伤势，或作为一次性魔力源使用；需定期净化，否则宝石会逐渐污浊并影响持有者情绪。',
    description: '寄宿少女灵魂的宝石，可供施法与修复伤势，需定期净化避免污浊。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_anywhere_door',
    name: '任意门',
    type: '道具',
    quality: '传说',
    tags: '[传送][限时][都市]',
    effect: '说出目的地后打开粉色传送门，可让少量人员通过；单次开启时间有限，未在关闭前通过的人会被留在原地。',
    description: '粉色传送门。说出目的地后打开，可让少量人员通过，单次开启时间有限。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_twin_blades_of_azzinoth',
    name: '埃辛诺斯战刃',
    type: '武器',
    quality: '传说',
    tags: '[近战][双持][敏捷]',
    effect: '一对弯月形战刃，适合高速近战；双持时威力倍增，但持续挥砍对体力与手腕负担极大，耐力不足时命中率会骤降。',
    description: '一对弯月形战刃，适合高速近战。双持时威力更强，但对使用者负担很大。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_ashbringer',
    name: '灰烬使者',
    type: '武器',
    quality: '传说',
    tags: '[圣光][斩灵][惩戒]',
    effect: '圣光属性双手剑，对亡灵、诅咒与黑暗力量造成额外伤害；挥舞时散发灼目圣光，可短暂压制邪祟气场。',
    description: '圣光属性双手剑，对亡灵、诅咒和黑暗力量有额外效果。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_elder_wand',
    name: '老魔杖',
    type: '武器',
    quality: '传说',
    tags: '[施法][易主][威权]',
    effect: '强力魔杖，可显著提升施法威能与命中；所有权会随击败或缴械自然转移，持有者若在决斗中落败，魔杖将立刻倒戈。',
    description: '强力魔杖，所有权会随击败或缴械转移。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_invisibility_cloak',
    name: '隐身衣',
    type: '衣物',
    quality: '传说',
    tags: '[潜行][遮蔽][奇幻]',
    effect: '穿戴后隐去外形，视觉上完全不可见；但声音、气味与触碰仍会暴露位置，剧烈动作或魔法侦测可识破。',
    description: '可覆盖身体的斗篷，穿戴后隐去外形，但声音、气味和触碰仍会暴露位置。',
    poolTags: ['奇幻', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_excalibur',
    name: '石中剑',
    type: '武器',
    quality: '传说',
    tags: '[王权][选择][契约]',
    effect: '只有被认可者能拔出使用。作为王权之剑，拔出后自动成为统治权或骑士资格的象征，对心怀不轨者会拒绝为其效力。',
    description: '传说中的王权之剑，只有被认可者能拔出。可作为统治权或骑士资格象征。',
    poolTags: ['奇幻', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_purple_gold_gourd',
    name: '紫金葫芦',
    type: '道具',
    quality: '传说',
    tags: '[封印][收摄][修真]',
    effect: '对准目标呼唤其真实姓名，若目标答应，会被缩小并困入葫芦；同时只能困住一人，被关者可在内部听到外界动静但无法逃脱。',
    description: '对准目标呼唤其真实姓名，若目标答应，会被缩小并困入葫芦；同时只能困住一人。',
    poolTags: ['修真', '历史', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_fengyue_baojian',
    name: '风月宝鉴',
    type: '道具',
    quality: '传说',
    tags: '[幻象][克欲][双面]',
    effect: '照正面显示满足内心欲望的幻象，引人沉溺；照背面得见红粉骷髅，可大幅抑制情欲、斩断执念。',
    description: '双面古镜。照正面时会显示满足使用者内心色欲的幻象，照背面时得见红粉骷髅，大幅度抑制情欲',
    poolTags: ['历史', '修真'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_wishing_phone_booth',
    name: '如意电话亭',
    type: '道具',
    quality: '神话',
    tags: '[愿望][一次性][因果]',
    effect: '在亭内拨通愿望电话并说出愿望，走出电话亭时愿望会以不容置疑的方式真切地变为现实；使用一次后自动销毁，愿望的实现方式总是出人意料。',
    description: '可拨打愿望电话的亭子。许出的愿望会在走出电话亭时以不容置疑的方式真切地变为现实，使用一次会自动销毁。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_death_note',
    name: '死亡笔记',
    type: '道具',
    quality: '神话',
    tags: '[因果][处决][追查]',
    effect: '写下真实姓名和死因后目标会死亡；使用者的记忆与现场会留下可被超自然手段追查的痕迹，滥用者终将付出代价。',
    description: '黑色笔记本。写下真实姓名和死因后目标会死亡；每次使用都会留下可追查痕迹。',
    poolTags: ['都市', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_thunderfury',
    name: '雷霆逐风剑',
    type: '武器',
    quality: '神话',
    tags: '[雷击][风暴][显眼]',
    effect: '可召唤雷电与强风进行大范围打击；每次召唤都伴随轰鸣与闪光，会明显暴露持有者的位置。',
    description: '风暴属性传说长剑，可召唤雷电和强风。使用时会明显暴露持有者位置。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'fantasy_philosophers_stone',
    name: '哲人石',
    type: '道具',
    quality: '神话',
    tags: '[炼金][转化][延寿]',
    effect: '可进行物质转化并制造延寿药剂；每次转化都需要稀有原料与漫长仪式，失败会损耗使用者的生命力。',
    description: '炼金圣物，可进行物质转化并制造延寿药剂，使用条件苛刻。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_jingu_bang',
    name: '金箍棒',
    type: '武器',
    quality: '神话',
    tags: '[伸缩][重击][定海]',
    effect: '可随心伸缩与改变重量的神兵，轻如鸿毛、重逾山岳；适合近战、支撑、破坏与压制大型目标，只有被认可者能自由掌控。',
    description: '可随心伸缩和改变重量的神兵，适合近战、支撑、破坏和压制大型目标。',
    poolTags: ['修真', '奇幻', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_heaven_bottle',
    name: '掌天瓶',
    type: '道具',
    quality: '神话',
    tags: '[催熟][灵液][蓄能]',
    effect: '神秘小瓶，可催熟灵药或积蓄特殊灵液；每次使用需要等待较长恢复时间，瓶内的灵液是修炼与炼丹的珍稀材料。',
    description: '神秘小瓶，可催熟灵药或积蓄特殊灵液。每次使用需要等待较长恢复时间。',
    poolTags: ['修真'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_shining_trapezohedron',
    name: '闪耀的偏方三八面体',
    type: '道具',
    quality: '神话',
    tags: '[隐秘知识][污染][注视]',
    effect: '凝视多面体可获得隐秘知识，越深入越接近真相；但每次凝视都会引来未知存在的注意，精神损耗逐渐累积。',
    description: '多面体黑石，凝视后可获得隐秘知识，但会引来未知存在的注意。',
    poolTags: ['历史', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_necronomicon',
    name: '死灵之书',
    type: '道具',
    quality: '神话',
    tags: '[禁忌知识][仪式][精神损耗]',
    effect: '阅读可获得禁忌仪式或神秘学信息，可用于召唤、封印与咒术；每读一页都会造成精神损耗，长期阅读会逐渐改变认知。',
    description: '记载禁忌知识的古书。阅读可获得仪式或神秘学信息，但会造成精神损耗。',
    poolTags: ['历史', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_flame_mantra',
    name: '焚决',
    type: '功法',
    quality: '神话',
    tags: '[功法][吞噬][进化]',
    effect: '可吞噬异火并进化的修炼功法；每吞噬一种强火源可提升阶位与火系威力，吞噬失败会造成严重反噬，甚至自焚经脉。',
    description: '可吞噬异火并进化的修炼功法。每吞噬一种强火源可提升阶位，失败会造成严重反噬。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_coin_railgun',
    name: '超电磁炮',
    type: '武器',
    quality: '传说',
    tags: '[电磁][远程][高耗]',
    effect: '以硬币等金属弹丸为介质发射高速电磁弹，射程远、穿透力强；每次发射消耗一枚弹丸与大量电力，弹道呈直线且极易吸引注意。',
    description: '以硬币等金属弹丸为介质发射高速电磁弹。每次发射消耗一枚金属弹丸和大量电力。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'school_revue_stage_device',
    name: '舞台装置',
    type: '道具',
    quality: '史诗',
    tags: '[领域][表演][限次]',
    effect: '可展开一座临时舞台，限定范围内的行动会被转化为表演、竞演或决斗形式，胜负由表现力与气势决定；每天只能使用一次。',
    description: '可展开一座临时舞台，限定范围内的行动会被转化为表演、竞演或决斗形式。每天一次。',
    poolTags: ['校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_at_field',
    name: 'AT立场',
    type: '道具',
    quality: '神话',
    tags: '[领域][防御][精神]',
    effect: '展开绝对领域，可抵挡一次大多数常规攻击；同类力场、精神干涉或极高威能可以穿透或削弱它，展开期间无法同时进行复杂行动。',
    description: '展开绝对领域，可抵挡一次大多数常规攻击；同类力场或精神干涉可削弱它。',
    poolTags: ['奇幻', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_rtx_5090',
    name: 'RTX 5090',
    type: '道具',
    quality: '传说',
    tags: '[计算][图形][高耗]',
    effect: '强大的图形与AI计算设备，可破解加密、训练模型或渲染虚拟世界；运行时耗电和发热极高，需要稳定供电，否则会过热降频。',
    description: '高端显卡，具备强大的图形和 AI 计算能力。运行时耗电和发热很高，需要稳定供电。',
    poolTags: ['都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'all_jinkela_fertilizer',
    name: '金坷垃',
    type: '材料',
    quality: '优秀',
    tags: '[肥料][增产][一次性]',
    effect: '可显著提高一片小型农田或盆栽的作物长势与产量，让枯苗转旺；每包只能使用一次，用量过大可能催出异常疯长的作物。',
    description: '肥料添加剂，可显著提高一片小型农田或盆栽的作物长势。每包只能使用一次。',
    poolTags: ['都市', '校园', '历史', '修真'],
    weight: 1.2,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_white_album',
    name: '白色相簿',
    type: '道具',
    quality: '优秀',
    tags: '[纪念][记录][校园]',
    effect: '可保存照片、票根和手写便签，被保存的记忆会在翻阅时鲜活重现；没有特殊能力，但承载的情感本身就是力量。',
    description: '白色封面的普通相簿，可保存照片、票根和手写便签，没有特殊能力。',
    poolTags: ['校园', '都市'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_computer_parts_package',
    name: '电脑配件',
    type: '任务物品',
    quality: '稀有',
    tags: '[伪装][禁忌][任务]',
    effect: '标注为电脑配件的密封包裹，内含催情用媚药；交给指定目标可推进任务，但拆封查看或截留会引发一连串麻烦。',
    description: '标注为电脑配件的密封包裹，内含催情用媚药。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_sword_of_benevolence',
    name: '仁之剑',
    type: '武器',
    quality: '史诗',
    tags: '[防御][统率][守约]',
    effect: '刘备双剑之一，重防守与统率，可为友军分担压力、稳定军心；一旦持有者违背仁义，剑的威能就会暂时失效。',
    description: '刘备双剑之一，重防守统率，违背仁义会失效。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'history_sword_of_righteousness',
    name: '义之剑',
    type: '武器',
    quality: '史诗',
    tags: '[支援][结盟][守约]',
    effect: '刘备双剑之一，重支援与结盟，能增强结盟之谊、凝聚同伴士气；一旦持有者背信弃义，剑的威能就会暂时失效。',
    description: '刘备双剑之一，重支援结盟，违背仁义会失效。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'history_imperial_jade_seal',
    name: '传国玉玺',
    type: '道具',
    quality: '神话',
    tags: '[天命][权柄][争夺]',
    effect: '可证明在中华地区绝对的天命与统治正当性，持有者在正统性判定中获得压倒性优势；展示时会引来各方争夺和追索。',
    description: '以和氏璧雕琢而成的玉玺，可证明在中华地区绝对的天命与统治正当性，无价之宝。展示时会引来争夺和追索。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_iron_certificate',
    name: '丹书铁券',
    type: '任务物品',
    quality: '传说',
    tags: '[免罪][凭证][历史]',
    effect: '刻有誓文的免罪凭证，可抵免一次重罪或死罪指控；对谋反、弑君等特例未必有效，出示时机不对可能招致更大猜忌。',
    description: '刻有誓文的免罪凭证，可抵免一次重罪或死罪指控；对谋反等特例未必有效。',
    poolTags: ['历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_sunflower_manual',
    name: '葵花宝典',
    type: '功法',
    quality: '神话',
    tags: '[功法][身法][代价]',
    effect: '自宫之后才可学习的高深武学秘籍，可显著提升速度、身法和细密招式修为；代价不可逆，且会彻底改变人生轨迹。',
    description: '自宫之后才可学习的高深武学秘籍，可显著提升速度、身法和细密招式修为。',
    poolTags: ['修真', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_eighty_nine_mystic_art',
    name: '八九玄功',
    type: '功法',
    quality: '神话',
    tags: '[功法][变化][肉身]',
    effect: '玄门护身变化之法，可强化肉身并进行多种变化（飞禽走兽、草木金石皆可）；变化越复杂越庞大，法力消耗越大，变化中受重创可能被迫现出原形。',
    description: '玄门护身变化之法，可强化肉身并进行多种变化。变化越复杂，消耗越大。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_huntian_sash',
    name: '混天绫',
    type: '衣物',
    quality: '传说',
    tags: '[缠缚][牵引][护身]',
    effect: '红色仙绫，可自动缠缚目标、牵引物体或在水中火中护身；对强力目标需要持续法力操控，被挣断后需法力温养复原。',
    description: '红色仙绫，可缠缚目标、牵引物体或在水火中护身。对强力目标需要持续操控。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_qiankun_ring',
    name: '乾坤圈',
    type: '饰品',
    quality: '传说',
    tags: '[投掷][护身][镇压]',
    effect: '金色法圈，可投掷打击、收回护身或压制妖邪；投出后需要召回才能再次使用，距离过远或目标过强时召回会异常吃力。',
    description: '金色法圈，可投掷打击、收回护身或压制妖邪。离手后需要召回才能再次使用。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_jade_purification_vase',
    name: '玉净瓶',
    type: '道具',
    quality: '神话',
    tags: '[收纳][灵水][净化]',
    effect: '白玉宝瓶，可盛放灵水并收纳小型目标，瓶内空间有限；强行收纳体型过大或反抗强烈的目标会快速消耗灵力，甚至损伤宝瓶。',
    description: '白玉宝瓶，可盛放灵水并收纳小型目标。瓶内空间有限，强行收纳会快速消耗灵力。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_nine_tooth_rake',
    name: '九齿钉耙',
    type: '武器',
    quality: '传说',
    tags: '[破甲][钩拽][重武]',
    effect: '九齿重兵器，擅长破甲、钩拽与大范围横扫；重量极高，力量不足者挥舞迟缓，命中要害可连人带甲拖拽过来。',
    description: '九齿重兵器，适合破甲、钩拽和大范围横扫。重量很高，使用者需要足够力量。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'cultivation_white_dragon_horse',
    name: '白龙马',
    type: '坐骑',
    quality: '神话',
    tags: '[坐骑][龙族][渡险]',
    effect: '可化为白马的龙族坐骑，日行千里、涉水渡险，危急时可短暂展露龙威震慑宵小；受重伤后会被迫现出龙形休养，短期内无法骑乘。',
    description: '可化为白马的龙族坐骑，能长途跋涉、涉水渡险。受重伤后需以龙形休养。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_raw_melon',
    name: '生瓜蛋子',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][生涩][都市]',
    effect: '勉强能吃的生瓜，口感生涩、水分不足；可以充饥，但吃完大概率让人摇头，适合拿来整蛊或自嘲。',
    description: '未熟透的瓜，口感生涩。',
    poolTags: ['都市'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_water_warding_pearl',
    name: '避水珠',
    type: '道具',
    quality: '稀有',
    tags: '[辟水][潜行][修真]',
    effect: '贴身携带可在水下短暂呼吸并避开普通水压，让潜游与水下探索变得轻松；遇到灵潮或深海暗流时效果会减弱，长时间深潜仍需留意气力。',
    description: '通透圆润的宝珠，贴身携带可在水下短暂呼吸并避开普通水压。遇到灵潮或深海暗流时效果会减弱。',
    poolTags: ['修真', '奇幻'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_herbal_milk_tea',
    name: '中药奶茶',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][养生][难喝]',
    effect: '带有中药味儿的奶茶，勉强下咽后获得一丝不明觉厉的安心感，据说对身体有那么一点点好处；味道会让人认真思考餐饮创新的边界。',
    description: '带有中药味儿的奶茶，味道一言难尽，让人认真思考餐饮创新的边界。',
    poolTags: ['都市', '校园'],
    weight: 1.3,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_hypnosis_app',
    name: '催眠APP',
    type: '道具',
    quality: '史诗',
    tags: '[催眠][洗脑][都市]',
    effect: '展示画面可施加强力催眠，让目标暂时接受暗示或指令；效果受目标意志与认知影响，意志坚定者可能清醒，滥用会留下严重后患。',
    description: '神秘手机应用，展示画面可施加强力催眠，效果受目标认知影响。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_scallion_pancake',
    name: '葱油饼',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][恢复][充饥]',
    effect: '外酥内软、葱香浓郁的热饼，食用后少量恢复体力，适合在路边快速充饥；吃完手上会留一股油香。',
    description: '外酥内软、葱香浓郁的热饼，食用后少量恢复体力，也适合在路边快速充饥。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_zhajiang_noodles',
    name: '炸酱面',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][恢复][充饥]',
    effect: '酱香浓厚的一碗面，食用后恢复少量体力和心情，吃完容易想再来一碗；老北京口味，讲究干拌趁热。',
    description: '酱香浓厚的一碗面，食用后恢复少量体力和心情，吃完容易想再来一碗。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fairy_crystal_slipper',
    name: '水晶鞋',
    type: '道具',
    quality: '史诗',
    tags: '[礼仪][时限][变身]',
    effect: '穿上后显著提升礼仪、舞蹈与第一印象，举手投足自带优雅；魔力在第一次穿着的当晚12点失效，之后鞋子会留在原地化为凡物。',
    description:
      '透明精致的鞋子，穿上后会显著提升礼仪、舞蹈和第一印象。第一次穿着的当晚12点前有效，之后魔力消失，鞋子会留在原地。',
    poolTags: ['奇幻', '校园', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fairy_poisoned_apple',
    name: '毒苹果',
    type: '消耗品',
    quality: '稀有',
    tags: '[沉睡][疗伤][一次性]',
    effect: '食用者陷入近似死亡的沉睡，期间外伤和疾病不会继续恶化，等于一次暂停的续命；只能使用一次，苏醒方式由使用者提前设定或等待真爱之吻。',
    description: '鲜红的苹果。食用者会陷入近似死亡的沉睡，期间外伤和疾病不会继续恶化。只能使用一次。',
    poolTags: ['奇幻', '历史'],
    weight: 1.1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fairy_little_match',
    name: '火柴',
    type: '材料',
    quality: '普通',
    tags: '[照明][点火][消耗]',
    effect: '普通火柴，可点火、照明或生火，也能短暂照亮黑暗；受潮后可能无法使用，火光会暴露位置但也能温暖人心。',
    description: '普通火柴，可以点火、照明或生火。受潮后可能无法使用。',
    poolTags: ['奇幻', '校园', '历史', '都市'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 8,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_raccoon_crispy_noodles',
    name: '小浣熊干脆面',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][恢复][怀旧]',
    effect: '童年味道的干脆面，捏碎后更香；食用后少量恢复体力和心情，袋里可能还藏着怀旧小卡片。',
    description: '童年味道的干脆面，捏碎后更香。食用后少量恢复体力和心情。',
    poolTags: ['都市', '校园'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_strawberry_milk',
    name: '草莓牛奶',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][恢复][甜味]',
    effect: '粉色纸盒装饮品，甜味很足；饮用后少量恢复精神，甜腻的口感能让人短暂忘记烦恼。',
    description: '粉色纸盒装饮品，甜味很足。饮用后少量恢复精神。',
    poolTags: ['都市', '校园'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_flashlight',
    name: '手电筒',
    type: '道具',
    quality: '普通',
    tags: '[照明][工具][都市]',
    effect: '便携照明工具，可照亮黑暗区域，也能当作简易自卫用具；电量不足时光线会变弱，记得及时换电池。',
    description: '便携照明工具，可照亮黑暗区域。电量不足时光线会变弱。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.3,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_membership_card',
    name: '会员卡',
    type: '道具',
    quality: '稀有',
    tags: '[折扣][双刃][都市]',
    effect: '任何消费都能五折，但持有者卖出物品时价格也会五折；买卖之间抉择，是最懂人心的会员卡。',
    description: '任何消费都能五折，但持有者卖出物品时价格也会五折。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_stebaker_car',
    name: '斯蒂庞克牌汽车',
    type: '道具',
    quality: '史诗',
    tags: '[载具][显眼][历史]',
    effect: '老派轿车，开上街极其显眼，是身份与权力的象征；车况良好但油耗惊人，维修配件难寻，也容易引来觊觎者。',
    description: '老派轿车，开上街极其显眼，是身份的象征。',
    poolTags: ['历史', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_golden_buddha_throne',
    name: '玉座金佛',
    type: '任务物品',
    quality: '传说',
    tags: '[贵重][任务][佛缘]',
    effect: '贵重佛像，蕴含深厚佛缘，交给应当归属之人可获大善缘；随身携带时出入寺院与佛门场景会得到格外优待，但也容易招来盗匪。',
    description: '贵重佛像，应该归属于值得的人。',
    poolTags: ['历史', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_red_pill',
    name: '红色药丸',
    type: '消耗品',
    quality: '传说',
    tags: '[真相][不可逆][都市]',
    effect: '吞下后即可看见隐藏在日常背后的真实，从此再也无法假装看不见；此举无法撤回，认知改变会永远持续。',
    description: '一旦吞下，即可看见隐藏在日常背后的真实。此举无法撤回。',
    poolTags: ['都市', '奇幻'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_blue_pill',
    name: '蓝色药丸',
    type: '消耗品',
    quality: '稀有',
    tags: '[遗忘][安抚][都市]',
    effect: '吞下后可忘记一切异常，回归安稳的日常；选择性遗忘让创伤与恐惧不再纠缠，但真相并不会消失，只是被暂时合上。',
    description: '吞下后可忘记一切异常，回归到安稳的日常。',
    poolTags: ['都市', '奇幻'],
    weight: 1.1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_memory_bread',
    name: '记忆面包',
    type: '消耗品',
    quality: '史诗',
    tags: '[记忆][学习][消化]',
    effect: '把文字印在面包上吃下即可记住内容，备考神器；消化后记忆可能逐渐消退，吃多了还可能拉肚子。',
    description: '把文字印在面包上吃下即可记住内容，消化后效果可能消退。',
    poolTags: ['校园', '都市'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'all_regret_medicine',
    name: '后悔药',
    type: '消耗品',
    quality: '神话',
    tags: '[回溯][一次性][因果]',
    effect: '一次性药丸，可让故事回溯到某个节点之前；只有服下者保留记忆，其他人会按原轨迹重演，命运不会给你第二次同样的选择。',
    description: '一次性药丸，可让故事回溯到某个节点之前。只能使用一次。',
    poolTags: ['奇幻', '修真', '都市', '校园', '历史'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_voice_recorder',
    name: '录音笔',
    type: '道具',
    quality: '优秀',
    tags: '[录音][取证][都市]',
    effect: '可长时间录音并保存证据，是谈判与调查的得力工具；嘈杂环境下需要贴近声源，小心被对方发现录音行为。',
    description: '可长时间录音并保存证据。嘈杂环境下需要贴近声源。',
    poolTags: ['都市', '校园'],
    weight: 1.2,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_devil_passport',
    name: '恶魔护照',
    type: '道具',
    quality: '神话',
    tags: '[说服][豁免][都市]',
    effect: '出示后可让对方允许或原谅持有者的任何行为，一次交涉中只能使用一次；过度使用会让目标逐渐产生警惕与反感。',
    description: '出示后可让对方允许或原谅持有者的任何行为。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_maliang_brush',
    name: '马良的笔',
    type: '道具',
    quality: '神话',
    tags: '[创造][幻真][奇幻]',
    effect: '神奇画笔，画出的事物可能化为现实；画得越细致越逼真，实体化越稳定，粗心大意画出来的东西可能失真甚至反噬。',
    description: '神奇画笔，画出的事物可能化为现实。',
    poolTags: ['奇幻', '历史', '修真'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_master_key',
    name: '万能钥匙',
    type: '道具',
    quality: '传说',
    tags: '[开锁][万能][代价]',
    effect: '可尝试打开几乎任何锁，从普通门锁到法阵封印都有一试之力；越复杂的封印越需要时间和代价，强行开启可能惊动锁的主人。',
    description: '可尝试打开几乎任何锁。越复杂的封印越需要时间和代价。',
    poolTags: ['都市', '校园', '奇幻', '历史'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_allezuhod_pen',
    name: '阿勒苏霍德之笔',
    type: '道具',
    quality: '神话',
    tags: '[改写现实][反噬][禁忌]',
    effect: '编号“0-08”。用这支笔写下的故事一定会成真，但是总会以离奇并讽刺的方式来反噬它的主人；每一次书写都在邀请不可控的因果。',
    description: '编号“0-08”。用这支笔写下的故事一定会成真，但是总会以离奇并讽刺的方式来反噬它的主人。',
    poolTags: ['奇幻', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_shrink_ray',
    name: '缩小灯',
    type: '道具',
    quality: '传说',
    tags: '[缩小][光效][电量]',
    effect: '照射目标可使其缩小，缩小比例与持续时间取决于电量；反光镜面或防护服可以抵挡效果，照到自己人会很尴尬。',
    description: '照射目标可使其缩小，持续时间和缩小比例取决于电量。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_voice_changer_bowtie',
    name: '变声器',
    type: '道具',
    quality: '史诗',
    tags: '[变声][伪装][都市]',
    effect: '蝴蝶结外观的变声器，可模拟他人声音；需要先听过目标声线，模仿越熟悉的声音越难被识破。',
    description: '蝴蝶结外观的变声器，可模拟他人声音。需要先听过目标声线。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_anesthetic_needle_watch',
    name: '麻醉针',
    type: '道具',
    quality: '史诗',
    tags: '[麻醉][偷袭][都市]',
    effect: '蝴蝶结机关发射的麻醉针，命中后让目标短暂昏睡；针头细小隐蔽，但发射有声响，防护衣物可以挡住。',
    description: '蝴蝶结机关发射的麻醉针，可让目标短暂昏睡。',
    poolTags: ['都市', '校园'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_golden_toilet',
    name: '黄金马桶',
    type: '道具',
    quality: '神话',
    tags: '[王座][帝国幻象][代价]',
    effect: '被戏称为黄金马桶的宏伟王座，能维持一片摇摇欲坠的帝国幻象，让坐上去的人仿佛掌握无边权柄；但会极度消耗持有者的生命与精神，区区凡人请勿久坐。',
    description: '被戏称为黄金马桶的宏伟王座，能维持一片摇摇欲坠的帝国幻象，但会极度消耗持有者。区区凡人请勿久坐。',
    poolTags: ['奇幻', '都市'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_molotov_cocktail',
    name: '燃烧瓶',
    type: '消耗品',
    quality: '优秀',
    tags: '[投掷][火焰][危险]',
    effect: '危险的投掷物，命中后制造短暂火焰和烟雾，可封锁通道或驱散人群；使用不当很容易伤到自己或引发更大麻烦。',
    description: '危险的投掷物，命中后会制造短暂火焰和烟雾。使用不当很容易伤到自己或引发更大麻烦。',
    poolTags: ['都市', '历史'],
    weight: 1.1,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_handgun',
    name: '手枪',
    type: '武器',
    quality: '稀有',
    tags: '[枪械][威慑][弹药]',
    effect: '常见小型枪械，可用于威慑和短距离自卫；弹药有限，开火会立刻引来注意，法律与道德的麻烦也随之而来。',
    description: '常见小型枪械，可用于威慑和短距离自卫。弹药有限，开火会立刻引来注意。',
    poolTags: ['都市', '历史'],
    weight: 1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'urban_wheelchair',
    name: '轮椅',
    type: '道具',
    quality: '普通',
    tags: '[移动][载具][便利]',
    effect: '结实的可折叠轮椅，可协助行动不便者移动，也能临时搬运伤员或少量物资；在轮椅上开枪时容易误伤队友，请务必注意安全。',
    description: '结实的可折叠轮椅，可协助行动不便者移动，也能临时搬运伤员或少量物资。在轮椅上开枪时容易误伤队友。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.2,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_mantou_slice_er',
    name: '馒头片儿',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][充饥][历史]',
    effect: '烤得焦香的馒头片儿，食用后恢复少量体力；客栈中的常见小食，等待制作的过程十分煎熬，但也别有一番风味。',
    description: '烤得焦香的馒头片儿，客栈中的常见小食。等待制作的过程十分煎熬。',
    poolTags: ['历史', '都市'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'history_mantou',
    name: '馒头',
    type: '消耗品',
    quality: '普通',
    tags: '[食物][充饥][历史]',
    effect: '白胖朴实的馒头，食用后快速充饥、恢复体力；搭配咸菜或汤水效果更好，是江湖路上最靠得住的干粮。',
    description: '白胖朴实的馒头，能快速充饥，搭配咸菜或汤水效果更好。',
    poolTags: ['历史', '都市', '修真'],
    weight: 1.5,
    stackable: true,
    unique: false,
    grantQuantity: 4,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_white_gloves',
    name: '白手套',
    type: '衣物',
    quality: '优秀',
    tags: '[无痕][精细][都市]',
    effect: '干净得过分的白手套，佩戴后在不留下指纹的情况下进行精细操作；也会让人一眼看出「此人不想留痕迹」。',
    description: '一副干净得过分的白手套，适合在不留下指纹的情况下进行精细操作。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'urban_black_gloves',
    name: '黑手套',
    type: '衣物',
    quality: '优秀',
    tags: '[潜入][伪装][夜行]',
    effect: '贴合手型的黑色手套，适合潜入、伪装和夜间行动，握持工具时更加稳当；低调配色在暗处几乎不反光。',
    description: '一副贴合手型的黑色手套，适合潜入、伪装和夜间行动，握持工具时也更加稳当。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1.1,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'equipment',
  },
  {
    id: 'school_yellow_duck',
    name: '小黄鸭',
    type: '道具',
    quality: '普通',
    tags: '[玩具][安抚][标记]',
    effect: '捏起来会发出轻响的黄色小鸭玩具；能缓和紧张气氛，也能在水面上当作醒目的小标记，关键时刻还能当浮标。',
    description: '捏起来会发出轻响的黄色小鸭玩具。能缓和紧张气氛，也能在水面上当作醒目的小标记。',
    poolTags: ['校园', '都市'],
    weight: 1.3,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_thermos',
    name: '暖水瓶',
    type: '道具',
    quality: '普通',
    tags: '[保温][盛装][都市]',
    effect: '保温效果不错的暖水瓶，可携带热水、药汤或临时需要保温的液体；外壳经不起剧烈碰撞，装满热水时更要小心。',
    description: '保温效果不错的暖水瓶，可携带热水、药汤或临时需要保温的液体，外壳经不起剧烈碰撞。',
    poolTags: ['都市', '校园', '历史'],
    weight: 1.2,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_piggy_bank',
    name: '猪猪存钱罐',
    type: '道具',
    quality: '稀有',
    tags: '[生财][积累][都市]',
    effect: '神奇的存钱罐。每过一段时间内部的财富会一点点增加，存入越多、生得越旺；打破罐子才能取出所有积蓄，请想清楚再动手。',
    description: '神奇的存钱罐。每过一段时间内部的财富会一点点增加。',
    poolTags: ['都市', '校园'],
    weight: 0.9,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_felix_felicis',
    name: '福灵剂',
    type: '消耗品',
    quality: '传说',
    tags: '[幸运][短效][反噬]',
    effect: '短时间内极大程度使人幸运的药剂，几乎可以心想事成；药效结束后的一段时间会变得极为不幸，事前的选择会决定事后偿还的方式。',
    description: '短时间内极大程度上使人变得幸运药剂，几乎可以心想事成。药效结束后的一段时间会变得极为不幸。',
    poolTags: ['奇幻', '校园'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_estus_flask',
    name: '原素瓶',
    type: '道具',
    quality: '史诗',
    tags: '[恢复][疗伤][圣火]',
    effect: '橙色小瓶，盛装着原素圣火；饮用可恢复伤势或精神，在篝火或圣火处会重新蓄满，是漫长旅途最可靠的伙伴。',
    description: '橙色小瓶。饮用可以恢复伤势或精神。',
    poolTags: ['奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'fantasy_scroll_of_town_portal',
    name: '回城卷轴',
    type: '消耗品',
    quality: '优秀',
    tags: '[传送][逃命][吟唱]',
    effect: '展开并完成短暂吟唱后可回到特定据点，是野外冒险的保命符；吟唱期间被打断会浪费卷轴并暴露坐标。',
    description: '展开并完成短暂吟唱后可回到特定据点；吟唱期间被打断会浪费卷轴并暴露坐标。',
    poolTags: ['奇幻', '修真', '历史'],
    weight: 1.2,
    stackable: true,
    unique: false,
    grantQuantity: 2,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_forget_sorrow_water',
    name: '忘忧水',
    type: '消耗品',
    quality: '稀有',
    tags: '[忘忧][记忆][修真]',
    effect: '一杯清甜无味的水。饮下可忘记一段与悲伤、恐惧或执念相关的重要记忆；被忘记的事并不会消失，只是再也无法想起。',
    description: '一杯清甜无味的水。饮下可忘记一段与悲伤、恐惧或执念相关的重要记忆。',
    poolTags: ['修真', '都市', '历史'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_mengpo_soup',
    name: '孟婆汤',
    type: '消耗品',
    quality: '传说',
    tags: '[斩断][诅咒][代价]',
    effect: '奈何桥边的忘川汤。饮下可彻底斩断旧怨、诅咒或精神污染，也会抹去所有珍贵关系与身份链接；恩怨两清，前尘尽断。',
    description: '奈何桥边的忘川汤。饮下可彻底斩断旧怨、诅咒或精神污染，也会抹去所有珍贵关系与身份链接。',
    poolTags: ['修真', '历史', '奇幻'],
    weight: 1,
    stackable: true,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_elixir_of_immortality',
    name: '长生不老药',
    type: '消耗品',
    quality: '神话',
    tags: '[长生][延寿][觊觎]',
    effect: '帝王方士梦寐以求的丹药。服下可停止衰老并抵抗常规疾病，但不会免除痛苦、封印或厄运，还会引来所有觊觎长生者的追杀与算计。',
    description:
      '帝王方士梦寐以求的丹药。服下可停止衰老并抵抗常规疾病，但不会免除痛苦、封印或厄运，还会引来所有觊觎长生者。',
    poolTags: ['修真', '历史', '奇幻'],
    weight: 1,
    stackable: true,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_portal_gun',
    name: '传送枪',
    type: '道具',
    quality: '神话',
    tags: '[传送][物理][危险]',
    effect: '手持设备，可在合适平面上制造两扇相连传送门，动量会被保留，制造出跨越空间的高速通道；电量、角度和落点错误都可能造成灾难。',
    description: '手持设备，可在合适平面上制造两扇相连传送门，动量会被保留，电量、角度和落点错误都可能造成灾难。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'cultivation_bigu_dan',
    name: '辟谷丹',
    type: '消耗品',
    quality: '普通',
    tags: '[辟谷][干粮][修真]',
    effect: '修行者常备丹丸。服下一粒可数日不饥不渴，省下饭钱与时间；但口中会残留草木苦味，期间对宴饮、香气和烟火气格外迟钝。',
    description: '修行者常备丹丸。服下一粒可数日不饥不渴，但口中会残留草木苦味，期间对宴饮、香气和烟火气格外迟钝。',
    poolTags: ['修真', '历史'],
    weight: 1.4,
    stackable: true,
    unique: false,
    grantQuantity: 3,
    rewardTarget: 'inventory',
  },
  {
    id: 'school_pencil_case',
    name: '铅笔盒',
    type: '道具',
    quality: '普通',
    tags: '[文具][收纳][校园]',
    effect: '装着铅笔、橡皮和尺子的铅笔盒，除了书写和画图，也适合收纳细小零件或临时藏下一张纸条；普普通通，但关键时刻总能用上。',
    description: '装着铅笔、橡皮和尺子的铅笔盒。除了书写和画图，也适合收纳细小零件或临时藏下一张纸条。',
    poolTags: ['校园', '都市'],
    weight: 1.4,
    stackable: false,
    unique: false,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
  {
    id: 'urban_time_machine',
    name: '时光机',
    type: '道具',
    quality: '神话',
    tags: '[时空][穿越][冷却]',
    effect: '可尝试前往过去或未来的机器，每次启动都可能制造时间偏差或分支，冷却时间很长；改变历史的结果从来不会按预期到来。',
    description: '可尝试前往过去或未来的机器，每次启动都可能制造时间偏差或分支，冷却时间很长。',
    poolTags: ['都市', '校园', '奇幻'],
    weight: 1,
    stackable: false,
    unique: true,
    grantQuantity: 1,
    rewardTarget: 'inventory',
  },
];
